### ISSUE TITLE
Shouldn't you pass user on authenticated requests only?

### ISSUE THREAD

**Issue by saturnonearth** [joysofcode/enterprise-stack#11]
The user should not really be passed via the root layout file as it is now:

<img width="620" alt="CleanShot 2023-04-24 at 19 00 18@2x" src="https://user-images.githubusercontent.com/12503538/234134025-16914cce-b0b0-41c5-b382-247f510babfb.png">

Per Lucia docs,

> However, this is discouraged as there’s no guarantee that this load function will re-run automatically on auth state change. Another reason to avoid this is that even if your route is protected and only authorized user can access it, TypeScript won’t know that:

https://lucia-auth.com/sveltekit/client-auth-state

Instead, it should be passed on each route load function

**Comment by ak4zh** [comment]
The authentication should be done in hooks instead.

**Comment by saturnonearth** [comment]
Yea it's debatable whether that is better or to just `validateUser` on every request and pass `user` in the return.

**Comment by matiadev** [comment]
Sorry for the late response!

This is fine because you need the user information for the `page` store and we validate the user in other `load` functions.

I cleaned up the code. 🧹
