### ISSUE TITLE
non-interactive element error from vite

### ISSUE THREAD

**Issue by yodacom** [joysofcode/enterprise-stack#12]
Errors I receive when boot up Enterprise Stack:
4:52:58 PM [vite-plugin-svelte] ssr compile in progress ...
4:52:59 PM [vite-plugin-svelte] /node_modules/.pnpm/@skeletonlabs+skeleton@1.1.0/node_modules/@skeletonlabs/skeleton/components/ListBox/ListBoxItem.svelte:54:0 A11y: Non-interactive element <label> cannot have interactive role 'option'
4:52:59 PM [vite-plugin-svelte] /node_modules/.pnpm/@skeletonlabs+skeleton@1.1.0/node_modules/@skeletonlabs/skeleton/components/Radio/RadioItem.svelte:37:0 A11y: Non-interactive element <label> cannot have interactive role 'radio'
4:52:59 PM [vite-plugin-svelte] /node_modules/.pnpm/@skeletonlabs+skeleton@1.1.0/node_modules/@skeletonlabs/skeleton/components/Tab/Tab.svelte:36:0 A11y: Non-interactive element <label> cannot have interactive role 'tab'

**Comment by matiadev** [comment]
I haven't seen this before but if Skeleton fixed that issue you shouldn't see it anymore if you update the dependencies.
