### ISSUE TITLE
Consider alternative ORM rather than Prisma

### ISSUE THREAD

**Issue by fnimick** [joysofcode/enterprise-stack#15]
Prisma doesn't use native SQL JOIN expressions for queries, which leads to poor performance on relational queries.

At the very least, this should be made clear as a drawback, and directions for replacing prisma with an alternative database client would be welcome.

**Comment by matiadev** [comment]
@fnimick I only have experience using Prisma, but I'm looking forward to trying out Kysely and Drizzle. Do you have any other recommendations?

**Comment by fnimick** [comment]
Unfortunately I have not found another ORM that has syntax as nice as prisma... but prisma's performance on anything beyond simple CRUD non-relational queries is truly horrendous and there's no way (or plan from the team) to fix it.

I personally use Drizzle because I approach my applications from a database-first mindset and when I want data, I think through the SQL queries necessary to get it in the format I need, rather than thinking on the entity level like prisma. It gives me lots of flexibility to do fancy stuff like e.g. given an entity ID, get that entity and the row after it in an ordering:

```ts
const init = tx
    .$with("init")
    .as(
      tx
        .select({ surveyId: surveySection.surveyId, index: surveySection.index })
        .from(surveySection)
        .where(eq(surveySection.id, sectionId))
    );
  const [section, nextSection] = await tx
    .with(init)
    .select()
    .from(surveySection)
    .leftJoin(init, sql`TRUE`)
    .leftJoin(survey, eq(survey.id, surveySection.surveyId))
    .where(and(eq(surveySection.surveyId, init.surveyId), gte(surveySection.index, init.index)))
    .orderBy(asc(surveySection.index))
    .limit(2);
```

This query calculates the index (unique order column for my case) of the passed-in ID, then uses that to select the first two rows with that index or greater, which gives me the row I want and the row after in a single efficient query.

This is far more efficient than the corresponding Prisma code, where the only option is to select with a JOIN (which would issue two sequential queries) for the initial entity, then issue another select afterward for the next entity in the ordering. Not only is this inefficient for the database to compute, but you now pay the cost of the api server -> database latency three times over. But I totally understand people not wanting to drop down to SQL manipulation at this level :) 

Kysely and Drizzle are both more query builders than ORMs. I would suggest TypeORM if you want a higher level of abstraction with model classes, relational CRUD, etc that still offers performance using SQL native functionality.

**Comment by matiadev** [comment]
Thank you! 😄

I'm going to look into it.

**Comment by hugotox** [comment]
+1 for Drizzle: great DX and great performance
