### ISSUE TITLE
license missing

### ISSUE THREAD

**Issue by bumi001** [joysofcode/enterprise-stack#17]
Hi, I am interested in adopting this project in another work. Can you please add a license file to this project?

**Comment by matiadev** [comment]
@bumi001 Done! 😄

**Comment by bumi001** [comment]
Thank you Matia! I just published my project at
https://github.com/bumi001/web3-sveltekit-bundle.

I made several changes to the enterprise stack. First I updated
package.json and dealt with the breaking changes. Then, I modified the
authentication flow and refactored the code under src/routes into two
paths. One path (authenticated) requires a valid session. The other path
(auth) manages sessions. I can push these changes to your repo if you would
like.

This is originally intended for use in a class project in a blockchain
course I am teaching. But I think it has wider use. So, I made it public.
