### ISSUE TITLE
Inconsistent usage of userId

### ISSUE THREAD

**Issue by ak4zh** [joysofcode/enterprise-stack#5]
In the Prisma schema, we use `user_id` for all foreign relations.
https://github.com/joysofcode/enterprise-stack/blob/bc87572789ed07dd7a6b1109e70bcc9cee04a7c2/prisma/schema.prisma#L39

But in some place we use `key.userId`, `user.userId`

https://github.com/joysofcode/enterprise-stack/blob/bc87572789ed07dd7a6b1109e70bcc9cee04a7c2/src/routes/(auth)/login/%2Bpage.server.ts#L32

https://github.com/joysofcode/enterprise-stack/blob/bc87572789ed07dd7a6b1109e70bcc9cee04a7c2/src/routes/(auth)/register/%2Bpage.server.ts#L37

Can we make it consistent to avoid confusion?

**Comment by matiadev** [comment]
I want to use the same example Lucia does to be more future-proof and if you start changing `user_id` to `userId` in the Prisma schema then you have to change everything else and I don't love snake case either.

I think people who have strong opinions are going to want to change other things which they don't like and that is fine.
